#ifndef OPERATIONALSCENARIO_SCSIM_MAPPING
#define OPERATIONALSCENARIO_SCSIM_MAPPING

#include "SmuTypes.h"
#include "OperationalScenario_type.h"

void _SCSIM_Mapping_Create();
static ControlUtils _SCSIM_BoolEntity_Control_Utils;
#include "OperationalScenario.h"
void _SCSIM_Mapping_OperationalScenario();

void* _SCSIM_Get_OperationalScenario_Handle(void* pInstance, int nHandleIdent, int* pIteratorFilter, int nSize);

extern ControlUtils _SCSIM_SSM_TR_Ground_1_OpPhases_Utils;
extern ControlUtils _SCSIM_SSM_st_Ground_OpPhases_Utils;
extern ControlUtils _SCSIM_SSM_TR_Launch_1_OpPhases_Utils;
extern ControlUtils _SCSIM_SSM_st_Launch_OpPhases_Utils;
extern ControlUtils _SCSIM_SSM_TR_readsensors_1_atacquisition_OpPhases_AttitudeAcquisition_Utils;
extern ControlUtils _SCSIM_SSM_TR_readsensors_2_atacquisition_OpPhases_AttitudeAcquisition_Utils;
extern ControlUtils _SCSIM_SSM_st_readsensors_OpPhases_AttitudeAcquisition_atacquisition_Utils;
extern ControlUtils _SCSIM_SSM_TR_refAttitude_1_atacquisition_OpPhases_AttitudeAcquisition_Utils;
extern ControlUtils _SCSIM_SSM_st_refAttitude_OpPhases_AttitudeAcquisition_atacquisition_Utils;
extern ControlUtils _SCSIM_SSM_TR_SafeMode_1_atacquisition_OpPhases_AttitudeAcquisition_Utils;
extern ControlUtils _SCSIM_SSM_st_SafeMode_OpPhases_AttitudeAcquisition_atacquisition_Utils;
extern ControlUtils _SCSIM_SSM_TR_AttitudeAcquisition_1_OpPhases_Utils;
extern ControlUtils _SCSIM_SSM_st_AttitudeAcquisition_OpPhases_Utils;
extern ControlUtils _SCSIM_SSM_TR_AttControl_1_NPhase_OpPhases_NormalPhase_Utils;
extern ControlUtils _SCSIM_SSM_TR_AttControl_2_NPhase_OpPhases_NormalPhase_Utils;
extern ControlUtils _SCSIM_SSM_st_AttControl_OpPhases_NormalPhase_NPhase_Utils;
extern ControlUtils _SCSIM_SSM_TR_Payload_2_NPhase_OpPhases_NormalPhase_Utils;
extern ControlUtils _SCSIM_SSM_TR_Payload_1_NPhase_OpPhases_NormalPhase_Utils;
extern ControlUtils _SCSIM_SSM_st_Payload_OpPhases_NormalPhase_NPhase_Utils;
extern ControlUtils _SCSIM_SSM_TR_SafeMode_1_NPhase_OpPhases_NormalPhase_Utils;
extern ControlUtils _SCSIM_SSM_st_SafeMode_OpPhases_NormalPhase_NPhase_Utils;
extern ControlUtils _SCSIM_SSM_TR_NormalPhase_1_OpPhases_Utils;
extern ControlUtils _SCSIM_SSM_st_NormalPhase_OpPhases_Utils;
static int _SCSIM_ClockActive_SSM_st_SafeMode_OpPhases_NormalPhase_NPhase(void*);
static int _SCSIM_ClockActive_SSM_st_Payload_OpPhases_NormalPhase_NPhase(void*);
static int _SCSIM_ClockActive_SSM_st_AttControl_OpPhases_NormalPhase_NPhase(void*);
static int _SCSIM_ClockActive_SSM_st_NormalPhase_OpPhases(void*);
static int _SCSIM_ClockActive_SSM_st_SafeMode_OpPhases_AttitudeAcquisition_atacquisition(void*);
static int _SCSIM_ClockActive_SSM_st_refAttitude_OpPhases_AttitudeAcquisition_atacquisition(void*);
static int _SCSIM_ClockActive_SSM_st_readsensors_OpPhases_AttitudeAcquisition_atacquisition(void*);
static int _SCSIM_ClockActive_SSM_st_AttitudeAcquisition_OpPhases(void*);
static int _SCSIM_ClockActive_SSM_st_Launch_OpPhases(void*);
static int _SCSIM_ClockActive_SSM_st_Ground_OpPhases(void*);

#endif /*OPERATIONALSCENARIO_SCSIM_MAPPING */
