#ifndef USER_MACROS_H
#define USER_MACROS_H
/*generated by SCADE Code Generator*/
#include "libraries/libmathext/macro_libmathext.h"
#include "libraries/libsmlk/macro_libsmlk.h"
#endif /*USER_MACROS_H*/
